// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRoBOopnccKxe20Pd16ZYZxXHLrssG7Ew',
    appId: '1:82009972349:web:1954398f2fb9bb3f6e5b14',
    messagingSenderId: '82009972349',
    projectId: 'flutter-test-ee3fb',
    authDomain: 'flutter-test-ee3fb.firebaseapp.com',
    storageBucket: 'flutter-test-ee3fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8wOo0N6CtgzM0IjK31OmIUDcxRDrCYfk',
    appId: '1:82009972349:android:93a4951254dae3826e5b14',
    messagingSenderId: '82009972349',
    projectId: 'flutter-test-ee3fb',
    storageBucket: 'flutter-test-ee3fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhkAv4Jdc4nOXLDi27VXTfjFjs-afvFi0',
    appId: '1:82009972349:ios:865587b4a67c490f6e5b14',
    messagingSenderId: '82009972349',
    projectId: 'flutter-test-ee3fb',
    storageBucket: 'flutter-test-ee3fb.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhkAv4Jdc4nOXLDi27VXTfjFjs-afvFi0',
    appId: '1:82009972349:ios:865587b4a67c490f6e5b14',
    messagingSenderId: '82009972349',
    projectId: 'flutter-test-ee3fb',
    storageBucket: 'flutter-test-ee3fb.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRoBOopnccKxe20Pd16ZYZxXHLrssG7Ew',
    appId: '1:82009972349:web:401d49d0063226f36e5b14',
    messagingSenderId: '82009972349',
    projectId: 'flutter-test-ee3fb',
    authDomain: 'flutter-test-ee3fb.firebaseapp.com',
    storageBucket: 'flutter-test-ee3fb.appspot.com',
  );
}
